# lr_plotting.py
# author: Jing Wen
# date: 2024-01-11

def plot_lr(X, y, weights):
    """Visualize the "lr_cd" linear regression model.

    This function takes actual data points and an estimated regression line,
    displaying them together in a scatter plot. The plot is also
    saved as a PNG image.
    
    Parameters
    ----------
    X: ndarray
        The observed data 'x', the independent variable
    
    y: ndarray
       The observed data 'y', the dependent variable. Both 'x' and 'y' should be continuous and of the same length.

    weights: ndarray
        Weights generated by 'lr_cd' function. It will be used to calculate the estimated values using the observed data 'x'.

    Returns
    -------
    A PNG image named 'linear_regression_plot.png' is saved.

    Examples
    --------
    >>> from lr_cd.lr_plotting import plot_lr
    >>> X = array([ 1.2390575 ,  1.99411649,  2.58284984,  2.37416463,  1.82673695,
    ...             1.71754177,  1.150911  ,  1.05020832, -0.28251291, -0.40102325])
    >>> y = array([ 2.3456723 ,  0.98456123,  3.1457892 ,  1.98765432,  2.9087645 ,
                    2.1345678 ,  0.12345678,  2.3456789 , -1.23456789, -0.12345678])
    >>> weights = array([ 1.88190714,  0.42167642])
    >>> plot_lr(X, y, weights)
    """
    